[package]
name = "adventofcode-2025"
version = "0.1.0"
edition = "2024"

[dependencies]
indoc = "2.0.7"
regex = "1.12.2"
itertools = "0.14.0"

[[bin]]
name = "day1"
path = "src/day1.rs"

[[bin]]
name = "day2"
path = "src/day2.rs"

[[bin]]
name = "day3"
path = "src/day3.rs"